### ISSUE TITLE
Port first draft schema from elmsln issue comment

### ISSUE THREAD

**Issue by profmikegreene** [LRNWebComponents/ontology#1]
https://github.com/elmsln/elmsln/issues/1927

**Comment by profmikegreene** [comment]
@btopro you know why I can't assign this to myself?

**Comment by btopro** [comment]
No... hmm.. maybe logout and log back in. I've noticed goofiness w/ repo role when logged in and just getting assigned stuff sometimes; your an admin of this repo tho so should
