### ISSUE TITLE
Atomic design info needed

### ISSUE THREAD

**Issue by profmikegreene** [LRNWebComponents/ontology#4]
I'm compiling my thoughts on how this and other next gen conversations relate to Duke at https://github.com/Duke-CIT/Learning-Technology-Ecosystem does any of that readme info belong in this repo?

**Comment by btopro** [comment]
Nice, that reads like some kind of world-view.md or something in this repo. It's important to think beyond single systems and this framing I think could help us communicate to others some examples and why these concepts are important.
